### ISSUE TITLE
Elisande's encounterID is wrong

### ISSUE THREAD

**Issue by AlexAtTheBux** [p3lim-wow/BonusRollPreview#21]
Line 39 of \encounters\Legion.lua should have Elisande listed as encounter 1872.  At some point in development she might have been 1743, as EJ_GetEncounterInfo(1743) still links to her but with a blank loot page.

**Comment by p3lim** [comment]
What region are you in? For me (enGB) 1743 has loot.

**Comment by p3lim** [comment]
Like I assumed (which is why I asked for region), it's the Galakras problem all over again, Blizzard assigned the boss two IDs (see #8).

Proof:
![](https://cloud.githubusercontent.com/assets/26496/23823812/d06b33f0-066a-11e7-91eb-b3f4cfba6df1.png)

I'll apply the same logic for her like I did with Galakras, thanks for reporting!
